name: Order Service CI

on:
  push:
    branches: [fix/security]
    paths:
      - "order-service/**"
      - ".github/workflows/order-service-ci.yml"
      - ".github/workflows/azure-containerapp-deploy.yml"

jobs:
  build-and-push:
    uses: ./.github/workflows/azure-containerapp-deploy.yml
    with:
      service_name: order-service
      service_path: order-service
      build_command: mvn clean package -DskipTests -B
      enable_sonar: true
      sonar_project_key: ${{ github.repository_owner }}_artisan-order-service
    secrets: inherit
