name: Review Service CI

on:
  push:
    branches: [fix/security]
    paths:
      - "review-service/**"
      - ".github/workflows/review-service-ci.yml"
      - ".github/workflows/azure-containerapp-deploy.yml"

jobs:
  build-and-push:
    uses: ./.github/workflows/azure-containerapp-deploy.yml
    with:
      service_name: review-service
      service_path: review-service
      build_command: mvn clean verify -B
      enable_sonar: true
      sonar_project_key: ${{ github.repository_owner }}_artisan-review-service
    secrets: inherit
    # secrets:
    #   ACR_LOGIN_SERVER: ${{ secrets.REVIEW_AZ2_ACR_LOGIN_SERVER }}
    #   ACR_USERNAME: ${{ secrets.REVIEW_AZ2_ACR_USERNAME }}
    #   ACR_PASSWORD: ${{ secrets.REVIEW_AZ2_ACR_PASSWORD }}
