name: User Service CI

on:
  push:
    branches: [fix/security]
    paths:
      - "user-service/**"
      - ".github/workflows/user-service-ci.yml"
      - ".github/workflows/azure-containerapp-deploy.yml"

jobs:
  build-and-push:
    uses: ./.github/workflows/azure-containerapp-deploy.yml
    with:
      service_name: user-service
      service_path: user-service
      build_command: mvn clean package -DskipTests -B
      enable_sonar: true
      sonar_project_key: ${{ github.repository_owner }}_artisan-user-service
    secrets: inherit
